### ISSUE TITLE
Crash on large file editing

### ISSUE THREAD

**Issue by darderik** [kayler-renslow/arma-intellij-plugin#27]
### Plugin Version

1.0.5_2
### Summary

Crash on file editing
### Detail

This [file ](https://github.com/ArmaLife/Framework/blob/master/life_server/Functions/MySQL/fn_queryRequest.sqf),when edited,causes a freeze of the IDE. Big files will also cause this.

**Comment by BangL** [comment]
i managed to get those freezes in a small file, this finally shows what the actual problem is.
i can tell pretty sure its somehow **related to for-loops** now.

pasting the following code snippet freezes my IDE 50% of the times... if thats not enough, just try to add a few more lines of code and your IDE will freeze.

`for "_i" from 0 to PMC_itemCtrlCount - 1 do {
    private _ctrl = (_display displayCtrl (40000 + _i));
    if (!isNull _ctrl) then {ctrlDelete _ctrl;};
};`

**Comment by kayler-renslow** [comment]
Well I found the problem. It's an infinite loop. This shouldn't take long to fix now.

**Comment by kayler-renslow** [comment]
And it's fixed for 1.0.6
