### ISSUE TITLE
breakOut expected String, got 'format'

### ISSUE THREAD

**Issue by Ragebone** [kayler-renslow/arma-intellij-plugin#6]

**Comment by kayler-renslow** [comment]
I need more than this....

**Comment by Ragebone** [comment]
ok, breakout takes a string.  breakOut "bla"; is ok
breakOut format["bla"]; should, but isn't.

**Comment by kayler-renslow** [comment]
breakOut format["bla"] is breaking out to a scopeName called "bla". Scopes are defined like: scopeName "bla". I'm not really sure what the point of formatting a scope name for breaking out is since the scopeName will be defined prior.
Like so:
`
scopeName "scope";  
{ breakOut "scope"; }forEach [1,2];
`
I already know how to fix this issue, but I'm curious to how you are setting scopeName.

**Comment by kayler-renslow** [comment]
fixed for next release
